/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by laravel-typescriptable
const Routes: Record<App.Route.Name, App.Route.Link> = {
  'sanctum.csrf-cookie': {
    name: 'sanctum.csrf-cookie',
    path: '/sanctum/csrf-cookie',
    params: undefined,
    methods: ['GET'],
  },
  'api/user': {
    name: 'api/user',
    path: '/api/user',
    params: undefined,
    methods: ['GET'],
  },
  'employees.index': {
    name: 'employees.index',
    path: '/api/employees',
    params: undefined,
    methods: ['GET'],
  },
  'employees.store': {
    name: 'employees.store',
    path: '/api/employees',
    params: undefined,
    methods: ['POST'],
  },
  'employees.show': {
    name: 'employees.show',
    path: '/api/employees/{employee}',
    params: {
      employee: 'string',
    },
    methods: ['GET'],
  },
  'employees.update': {
    name: 'employees.update',
    path: '/api/employees/{employee}',
    params: {
      employee: 'string',
    },
    methods: ['PUT', 'PATCH'],
  },
  'employees.destroy': {
    name: 'employees.destroy',
    path: '/api/employees/{employee}',
    params: {
      employee: 'string',
    },
    methods: ['DELETE'],
  },
  'devices.index': {
    name: 'devices.index',
    path: '/api/devices',
    params: undefined,
    methods: ['GET'],
  },
  'devices.store': {
    name: 'devices.store',
    path: '/api/devices',
    params: undefined,
    methods: ['POST'],
  },
  'devices.show': {
    name: 'devices.show',
    path: '/api/devices/{device}',
    params: {
      device: 'string',
    },
    methods: ['GET'],
  },
  'devices.update': {
    name: 'devices.update',
    path: '/api/devices/{device}',
    params: {
      device: 'string',
    },
    methods: ['PUT', 'PATCH'],
  },
  'devices.destroy': {
    name: 'devices.destroy',
    path: '/api/devices/{device}',
    params: {
      device: 'string',
    },
    methods: ['DELETE'],
  },
  'devices.employees.index': {
    name: 'devices.employees.index',
    path: '/api/devices/{device}/employees',
    params: {
      device: 'string',
    },
    methods: ['GET'],
  },
  'devices.employees.store': {
    name: 'devices.employees.store',
    path: '/api/devices/{device}/employees',
    params: {
      device: 'string',
    },
    methods: ['POST'],
  },
  'devices.employees.show': {
    name: 'devices.employees.show',
    path: '/api/devices/{device}/employees/{employee}',
    params: {
      device: 'string',
      employee: 'string',
    },
    methods: ['GET'],
  },
  'devices.employees.update': {
    name: 'devices.employees.update',
    path: '/api/devices/{device}/employees/{employee}',
    params: {
      device: 'string',
      employee: 'string',
    },
    methods: ['PUT', 'PATCH'],
  },
  'devices.employees.destroy': {
    name: 'devices.employees.destroy',
    path: '/api/devices/{device}/employees/{employee}',
    params: {
      device: 'string',
      employee: 'string',
    },
    methods: ['DELETE'],
  },
  'shifts.index': {
    name: 'shifts.index',
    path: '/api/shifts',
    params: undefined,
    methods: ['GET'],
  },
  'shifts.store': {
    name: 'shifts.store',
    path: '/api/shifts',
    params: undefined,
    methods: ['POST'],
  },
  'shifts.show': {
    name: 'shifts.show',
    path: '/api/shifts/{shift}',
    params: {
      shift: 'string',
    },
    methods: ['GET'],
  },
  'shifts.update': {
    name: 'shifts.update',
    path: '/api/shifts/{shift}',
    params: {
      shift: 'string',
    },
    methods: ['PUT', 'PATCH'],
  },
  'shifts.destroy': {
    name: 'shifts.destroy',
    path: '/api/shifts/{shift}',
    params: {
      shift: 'string',
    },
    methods: ['DELETE'],
  },
  'fingerprints.index': {
    name: 'fingerprints.index',
    path: '/api/fingerprints',
    params: undefined,
    methods: ['GET'],
  },
  'fingerprints.store': {
    name: 'fingerprints.store',
    path: '/api/fingerprints',
    params: undefined,
    methods: ['POST'],
  },
  'fingerprints.show': {
    name: 'fingerprints.show',
    path: '/api/fingerprints/{fingerprint}',
    params: {
      fingerprint: 'string',
    },
    methods: ['GET'],
  },
  'fingerprints.update': {
    name: 'fingerprints.update',
    path: '/api/fingerprints/{fingerprint}',
    params: {
      fingerprint: 'string',
    },
    methods: ['PUT', 'PATCH'],
  },
  'fingerprints.destroy': {
    name: 'fingerprints.destroy',
    path: '/api/fingerprints/{fingerprint}',
    params: {
      fingerprint: 'string',
    },
    methods: ['DELETE'],
  },
  'api/statistics': {
    name: 'api/statistics',
    path: '/api/statistics',
    params: undefined,
    methods: ['GET'],
  },
  'api/calendar': {
    name: 'api/calendar',
    path: '/api/calendar',
    params: undefined,
    methods: ['GET'],
  },
  'employees.fingerprints.index': {
    name: 'employees.fingerprints.index',
    path: '/api/employees/{employee}/fingerprints',
    params: {
      employee: 'string',
    },
    methods: ['GET'],
  },
  'employees.fingerprints.store': {
    name: 'employees.fingerprints.store',
    path: '/api/employees/{employee}/fingerprints',
    params: {
      employee: 'string',
    },
    methods: ['POST'],
  },
  'employees.fingerprints.show': {
    name: 'employees.fingerprints.show',
    path: '/api/employees/{employee}/fingerprints/{fingerprint}',
    params: {
      employee: 'string',
      fingerprint: 'string',
    },
    methods: ['GET'],
  },
  'employees.fingerprints.update': {
    name: 'employees.fingerprints.update',
    path: '/api/employees/{employee}/fingerprints/{fingerprint}',
    params: {
      employee: 'string',
      fingerprint: 'string',
    },
    methods: ['PUT', 'PATCH'],
  },
  'employees.fingerprints.destroy': {
    name: 'employees.fingerprints.destroy',
    path: '/api/employees/{employee}/fingerprints/{fingerprint}',
    params: {
      employee: 'string',
      fingerprint: 'string',
    },
    methods: ['DELETE'],
  },
  'api/scan': {
    name: 'api/scan',
    path: '/api/scan',
    params: undefined,
    methods: ['POST'],
  },
  'api/sync': {
    name: 'api/sync',
    path: '/api/sync',
    params: undefined,
    methods: ['GET'],
  },
  'api/queue': {
    name: 'api/queue',
    path: '/api/queue',
    params: undefined,
    methods: ['GET'],
  },
  'api/fingerprints/enroll': {
    name: 'api/fingerprints/enroll',
    path: '/api/fingerprints/enroll',
    params: undefined,
    methods: ['POST'],
  },
  'api/fingerprints/delete': {
    name: 'api/fingerprints/delete',
    path: '/api/fingerprints/delete',
    params: undefined,
    methods: ['POST'],
  },
  'up': {
    name: 'up',
    path: '/up',
    params: undefined,
    methods: ['GET'],
  },
  '/': {
    name: '/',
    path: '/',
    params: undefined,
    methods: ['GET'],
  },
}

declare global {
  interface Window {
    Routes: Record<App.Route.Name, App.Route.Link>
  }
}

const appUrl = 'http://127.0.0.1'

if (typeof window !== 'undefined') {
  if (typeof window !== 'undefined' && typeof window?.Routes !== 'undefined')
    window.Routes = Routes
}

export { Routes, appUrl }
